import '@testing-library/jest-dom/vitest'
import type { DesktopApi } from '../../preload/index.js'
import { useWorkspaceStore } from '../stores/workspaceStore'

// window.sapOpsDesktop IPC 목킹
const mockApi: { [K in keyof DesktopApi]: ReturnType<typeof vi.fn> } = {
  setApiKey: vi.fn().mockResolvedValue(undefined),
  getAuthStatus: vi.fn().mockResolvedValue('unauthenticated'),
  logout: vi.fn().mockResolvedValue(undefined),
  sendMessage: vi.fn().mockResolvedValue({
    session: { id: 's1', title: '테스트', provider: 'openai', model: 'gpt-4.1-mini', createdAt: '', updatedAt: '' },
    userMessage: { id: 'm1', sessionId: 's1', role: 'user', content: '테스트', inputTokens: 0, outputTokens: 0, createdAt: '' },
    assistantMessage: { id: 'm2', sessionId: 's1', role: 'assistant', content: '응답', inputTokens: 0, outputTokens: 10, createdAt: '' },
    meta: {
      skillUsed: 'cbo-impact-analysis',
      skillTitle: 'CBO 변경 영향 분석',
      sources: [{ title: 'Workspace Context', category: 'workspace', relevance_score: 1 }],
      sourceIds: ['workspace-context'],
      sourceCount: 1,
      suggestedTcodes: ['SE80'],
    },
  }),
  listSkills: vi.fn().mockResolvedValue([
    {
      id: 'cbo-impact-analysis',
      title: 'CBO 변경 영향 분석',
      description: 'CBO 영향 분석',
      supportedDomainPacks: ['cbo-maintenance'],
      supportedDataTypes: ['chat', 'cbo'],
      allowedSecurityModes: ['secure-local', 'reference', 'hybrid-approved'],
      defaultPromptTemplate: '',
      outputFormat: 'structured-report',
      requiredSources: ['workspace-context', 'vault-confidential'],
      suggestedInputs: ['이 변경이 어떤 객체에 영향을 주는지 정리해줘'],
      suggestedTcodes: ['SE80'],
    },
  ]),
  listSkillPacks: vi.fn().mockResolvedValue([
    {
      id: 'cbo-ops-starter',
      title: 'CBO + Ops Starter Pack',
      description: 'CBO와 운영 중심 skill pack',
      audience: 'mixed',
      domainPacks: ['ops', 'cbo-maintenance', 'functional'],
      skillIds: ['cbo-impact-analysis', 'incident-triage', 'transport-risk-review'],
    },
  ]),
  recommendSkills: vi.fn().mockResolvedValue([
    {
      skill: {
        id: 'cbo-impact-analysis',
        title: 'CBO 변경 영향 분석',
        description: 'CBO 영향 분석',
        supportedDomainPacks: ['cbo-maintenance'],
        supportedDataTypes: ['chat', 'cbo'],
        allowedSecurityModes: ['secure-local', 'reference', 'hybrid-approved'],
        defaultPromptTemplate: '',
        outputFormat: 'structured-report',
        requiredSources: ['workspace-context', 'vault-confidential'],
        suggestedInputs: ['이 변경이 어떤 객체에 영향을 주는지 정리해줘'],
        suggestedTcodes: ['SE80'],
      },
      reason: '현재 Domain Pack과 가장 잘 맞는 기본 작업입니다.',
      recommendedSourceIds: ['workspace-context', 'vault-confidential'],
    },
  ]),
  listSources: vi.fn().mockResolvedValue([
    {
      id: 'workspace-context',
      title: 'Workspace Context',
      description: '현재 워크스페이스 설정',
      kind: 'workspace',
      classification: 'mixed',
      domainPack: 'cbo-maintenance',
      availability: 'ready',
      sourceType: 'workspace_context',
    },
    {
      id: 'vault-confidential',
      title: 'Confidential Vault',
      description: '기밀 운영 지식',
      kind: 'vault',
      classification: 'confidential',
      domainPack: 'cbo-maintenance',
      availability: 'ready',
      sourceType: 'internal_memo',
    },
  ]),
  searchSources: vi.fn().mockResolvedValue([]),
  listConfiguredSources: vi.fn().mockResolvedValue([
    {
      id: 'src1',
      kind: 'local-folder',
      title: 'FI CBO Sources',
      rootPath: 'C:/sap/cbo',
      domainPack: 'cbo-maintenance',
      classificationDefault: 'confidential',
      includeGlobs: ['**/*.txt', '**/*.md'],
      enabled: true,
      syncStatus: 'ready',
      lastIndexedAt: new Date().toISOString(),
      documentCount: 2,
      connectionMeta: null,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  ]),
  pickAndAddLocalFolderSource: vi.fn().mockResolvedValue({
    canceled: false,
    source: {
      id: 'src2',
      kind: 'local-folder',
      title: '신규 Source',
      rootPath: 'C:/sap/new-source',
      domainPack: 'cbo-maintenance',
      classificationDefault: 'confidential',
      includeGlobs: ['**/*.txt', '**/*.md'],
      enabled: true,
      syncStatus: 'ready',
      lastIndexedAt: new Date().toISOString(),
      documentCount: 1,
      connectionMeta: null,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    summary: { indexed: 1, skipped: 0, failed: 0 },
  }),
  reindexSource: vi.fn().mockResolvedValue({
    source: {
      id: 'src1',
      kind: 'local-folder',
      title: 'FI CBO Sources',
      rootPath: 'C:/sap/cbo',
      domainPack: 'cbo-maintenance',
      classificationDefault: 'confidential',
      includeGlobs: ['**/*.txt', '**/*.md'],
      enabled: true,
      syncStatus: 'ready',
      lastIndexedAt: new Date().toISOString(),
      documentCount: 2,
      connectionMeta: null,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    summary: { indexed: 2, skipped: 0, failed: 0 },
  }),
  searchSourceDocuments: vi.fn().mockResolvedValue([
    {
      id: 'doc1',
      sourceId: 'src1',
      relativePath: 'billing/zsd_billing.txt',
      absolutePath: 'C:/sap/cbo/billing/zsd_billing.txt',
      title: 'zsd_billing.txt',
      excerpt: 'FORM validate_authority ...',
      contentText: 'REPORT ZSD_BILLING.',
      contentHash: 'hash-1',
      domainPack: 'cbo-maintenance',
      classification: 'confidential',
      tags: ['local-folder', 'cbo-maintenance'],
      indexedAt: new Date().toISOString(),
    },
  ]),
  getSourceDocument: vi.fn().mockResolvedValue({
    id: 'doc1',
    sourceId: 'src1',
    relativePath: 'billing/zsd_billing.txt',
    absolutePath: 'C:/sap/cbo/billing/zsd_billing.txt',
    title: 'zsd_billing.txt',
    excerpt: 'FORM validate_authority ...',
    contentText: 'REPORT ZSD_BILLING.',
    contentHash: 'hash-1',
    domainPack: 'cbo-maintenance',
    classification: 'confidential',
    tags: ['local-folder', 'cbo-maintenance'],
    indexedAt: new Date().toISOString(),
  }),
  listSessions: vi.fn().mockResolvedValue([]),
  getSessionMessages: vi.fn().mockResolvedValue([]),
  analyzeCboText: vi.fn().mockResolvedValue({ summary: '', risks: [], recommendations: [], metadata: { fileName: '', charCount: 0, languageHint: 'unknown' } }),
  analyzeCboFile: vi.fn().mockResolvedValue({ summary: '', risks: [], recommendations: [], metadata: { fileName: '', charCount: 0, languageHint: 'unknown' } }),
  analyzeCboFolder: vi.fn().mockResolvedValue({ run: {}, errors: [] }),
  pickAndAnalyzeCboFile: vi.fn().mockResolvedValue({ canceled: true, filePath: null, result: null }),
  pickAndAnalyzeCboFolder: vi.fn().mockResolvedValue({ canceled: true, rootPath: null, output: null }),
  listCboRuns: vi.fn().mockResolvedValue([]),
  getCboRunDetail: vi.fn().mockResolvedValue({ run: {}, files: [] }),
  syncCboRunKnowledge: vi.fn().mockResolvedValue({ runId: '', mode: 'bulk', endpoint: '', totalCandidates: 0, synced: 0, failed: 0, failures: [] }),
  diffCboRuns: vi.fn().mockResolvedValue({ fromRunId: '', toRunId: '', added: 0, resolved: 0, persisted: 0, changes: [] }),
  cancelCboFolder: vi.fn().mockResolvedValue(undefined),
  onCboProgress: vi.fn().mockReturnValue(() => {}),
  listAuditLogs: vi.fn().mockResolvedValue([]),
  searchAuditLogs: vi.fn().mockResolvedValue([]),
  listVaultEntries: vi.fn().mockResolvedValue([]),
  searchVaultByClassification: vi.fn().mockResolvedValue([]),
  listVaultByDomainPack: vi.fn().mockResolvedValue([]),
  listSessionsFiltered: vi.fn().mockResolvedValue([]),
  updateSessionTodoState: vi.fn().mockResolvedValue(undefined),
  toggleSessionFlag: vi.fn().mockResolvedValue(undefined),
  toggleSessionArchive: vi.fn().mockResolvedValue(undefined),
  addSessionLabel: vi.fn().mockResolvedValue(undefined),
  removeSessionLabel: vi.fn().mockResolvedValue(undefined),
  getSessionStats: vi.fn().mockResolvedValue({
    all: 0, open: 0, analyzing: 0, "in-progress": 0,
    resolved: 0, closed: 0, flagged: 0, archived: 0,
  }),
  getOAuthAvailability: vi.fn().mockResolvedValue([
    { provider: 'openai', available: true },
    { provider: 'anthropic', available: false },
    { provider: 'google', available: false },
  ]),
  initiateOAuth: vi.fn().mockResolvedValue({
    authUrl: 'https://auth.openai.com/authorize?...',
    provider: 'openai',
    useCallbackServer: true,
  }),
  waitOAuthCallback: vi.fn().mockResolvedValue({
    provider: 'openai',
    status: 'authenticated',
    accountHint: 'user@example.com',
    authType: 'oauth',
    updatedAt: new Date().toISOString(),
  }),
  cancelOAuth: vi.fn().mockResolvedValue(undefined),
  submitOAuthCode: vi.fn().mockResolvedValue({
    provider: 'anthropic',
    status: 'authenticated',
    accountHint: 'user@anthropic.com',
    authType: 'oauth',
    updatedAt: new Date().toISOString(),
  }),
}

Object.defineProperty(window, 'sapOpsDesktop', {
  value: mockApi,
  writable: true,
})

// 각 테스트 전에 모든 mock 초기화
beforeEach(() => {
  Object.values(mockApi).forEach((fn) => fn.mockClear())
})

// workspaceStore 초기화를 위한 헬퍼
export function resetWorkspaceStore() {
  useWorkspaceStore.setState({
    securityMode: 'secure-local',
    domainPack: 'ops',
  })
}

export { mockApi }
