import '@testing-library/jest-dom/vitest'
import type { DesktopApi } from '../../preload/index.js'
import { useWorkspaceStore } from '../stores/workspaceStore'

// window.sapOpsDesktop IPC 목킹
const mockApi: { [K in keyof DesktopApi]: ReturnType<typeof vi.fn> } = {
  setApiKey: vi.fn().mockResolvedValue(undefined),
  getAuthStatus: vi.fn().mockImplementation((provider: string) => Promise.resolve({
    provider,
    status: 'authenticated',
    accountHint: 'test@example.com',
    updatedAt: new Date().toISOString(),
  })),
  logout: vi.fn().mockResolvedValue(undefined),
  sendMessage: vi.fn().mockResolvedValue({
    session: { id: 's1', title: '테스트', provider: 'openai', model: 'gpt-4.1-mini', createdAt: '', updatedAt: '' },
    userMessage: { id: 'm1', sessionId: 's1', role: 'user', content: '테스트', inputTokens: 0, outputTokens: 0, createdAt: '' },
    assistantMessage: { id: 'm2', sessionId: 's1', role: 'assistant', content: '응답', inputTokens: 0, outputTokens: 10, createdAt: '' },
    meta: {
      skillUsed: 'cbo-impact-analysis',
      skillTitle: 'CBO 변경 영향 분석',
      sources: [{ title: 'Workspace Context', category: 'workspace', relevance_score: 1 }],
      sourceIds: ['workspace-context'],
      sourceCount: 1,
      suggestedTcodes: ['SE80'],
    },
  }),
  listSkills: vi.fn().mockResolvedValue([
    {
      id: 'cbo-impact-analysis',
      title: 'CBO 변경 영향 분석',
      description: 'CBO 영향 분석',
      supportedDomainPacks: ['cbo-maintenance'],
      supportedDataTypes: ['chat', 'cbo'],
      defaultPromptTemplate: '',
      outputFormat: 'structured-report',
      requiredSources: ['workspace-context', 'vault-confidential'],
      suggestedInputs: ['이 변경이 어떤 객체에 영향을 주는지 정리해줘'],
      suggestedTcodes: ['SE80'],
    },
  ]),
  listSkillPacks: vi.fn().mockResolvedValue([
    {
      id: 'cbo-ops-starter',
      title: 'CBO + Ops Starter Pack',
      description: 'CBO와 운영 중심 skill pack',
      audience: 'mixed',
      domainPacks: ['ops', 'cbo-maintenance', 'functional'],
      skillIds: ['cbo-impact-analysis', 'incident-triage', 'transport-risk-review'],
    },
  ]),
  recommendSkills: vi.fn().mockResolvedValue([
    {
      skill: {
        id: 'cbo-impact-analysis',
        title: 'CBO 변경 영향 분석',
        description: 'CBO 영향 분석',
        supportedDomainPacks: ['cbo-maintenance'],
        supportedDataTypes: ['chat', 'cbo'],
        defaultPromptTemplate: '',
        outputFormat: 'structured-report',
        requiredSources: ['workspace-context', 'vault-confidential'],
        suggestedInputs: ['이 변경이 어떤 객체에 영향을 주는지 정리해줘'],
        suggestedTcodes: ['SE80'],
      },
      reason: '현재 Domain Pack과 가장 잘 맞는 기본 작업입니다.',
      recommendedSourceIds: ['workspace-context', 'vault-confidential'],
    },
  ]),
  listSources: vi.fn().mockResolvedValue([
    {
      id: 'workspace-context',
      title: 'Workspace Context',
      description: '현재 워크스페이스 설정',
      kind: 'workspace',
      classification: 'mixed',
      domainPack: 'cbo-maintenance',
      availability: 'ready',
      sourceType: 'workspace_context',
    },
    {
      id: 'vault-confidential',
      title: 'Confidential Vault',
      description: '기밀 운영 지식',
      kind: 'vault',
      classification: 'confidential',
      domainPack: 'cbo-maintenance',
      availability: 'ready',
      sourceType: 'internal_memo',
    },
  ]),
  stopGeneration: vi.fn().mockResolvedValue(undefined),
  searchSources: vi.fn().mockResolvedValue([]),
  listConfiguredSources: vi.fn().mockResolvedValue([
    {
      id: 'src1',
      kind: 'local-folder',
      title: 'FI CBO Sources',
      rootPath: 'C:/sap/cbo',
      domainPack: 'cbo-maintenance',
      classificationDefault: 'confidential',
      includeGlobs: ['**/*.txt', '**/*.md'],
      enabled: true,
      syncStatus: 'ready',
      lastIndexedAt: new Date().toISOString(),
      documentCount: 2,
      connectionMeta: null,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  ]),
  pickAndAddLocalFolderSource: vi.fn().mockResolvedValue({
    canceled: false,
    source: {
      id: 'src2',
      kind: 'local-folder',
      title: '신규 Source',
      rootPath: 'C:/sap/new-source',
      domainPack: 'cbo-maintenance',
      classificationDefault: 'confidential',
      includeGlobs: ['**/*.txt', '**/*.md'],
      enabled: true,
      syncStatus: 'ready',
      lastIndexedAt: new Date().toISOString(),
      documentCount: 1,
      connectionMeta: null,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    summary: { indexed: 1, skipped: 0, failed: 0 },
  }),
  reindexSource: vi.fn().mockResolvedValue({
    source: {
      id: 'src1',
      kind: 'local-folder',
      title: 'FI CBO Sources',
      rootPath: 'C:/sap/cbo',
      domainPack: 'cbo-maintenance',
      classificationDefault: 'confidential',
      includeGlobs: ['**/*.txt', '**/*.md'],
      enabled: true,
      syncStatus: 'ready',
      lastIndexedAt: new Date().toISOString(),
      documentCount: 2,
      connectionMeta: null,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    summary: { indexed: 2, skipped: 0, failed: 0 },
  }),
  searchSourceDocuments: vi.fn().mockResolvedValue([
    {
      id: 'doc1',
      sourceId: 'src1',
      relativePath: 'billing/zsd_billing.txt',
      absolutePath: 'C:/sap/cbo/billing/zsd_billing.txt',
      title: 'zsd_billing.txt',
      excerpt: 'FORM validate_authority ...',
      contentText: 'REPORT ZSD_BILLING.',
      contentHash: 'hash-1',
      domainPack: 'cbo-maintenance',
      classification: 'confidential',
      tags: ['local-folder', 'cbo-maintenance'],
      indexedAt: new Date().toISOString(),
    },
  ]),
  getSourceDocument: vi.fn().mockResolvedValue({
    id: 'doc1',
    sourceId: 'src1',
    relativePath: 'billing/zsd_billing.txt',
    absolutePath: 'C:/sap/cbo/billing/zsd_billing.txt',
    title: 'zsd_billing.txt',
    excerpt: 'FORM validate_authority ...',
    contentText: 'REPORT ZSD_BILLING.',
    contentHash: 'hash-1',
    domainPack: 'cbo-maintenance',
    classification: 'confidential',
    tags: ['local-folder', 'cbo-maintenance'],
    indexedAt: new Date().toISOString(),
  }),
  listSessions: vi.fn().mockResolvedValue([]),
  getSessionMessages: vi.fn().mockResolvedValue([]),
  analyzeCboText: vi.fn().mockResolvedValue({ summary: '', risks: [], recommendations: [], metadata: { fileName: '', charCount: 0, languageHint: 'unknown' } }),
  analyzeCboFile: vi.fn().mockResolvedValue({ summary: '', risks: [], recommendations: [], metadata: { fileName: '', charCount: 0, languageHint: 'unknown' } }),
  analyzeCboFolder: vi.fn().mockResolvedValue({ run: {}, errors: [] }),
  pickAndAnalyzeCboFile: vi.fn().mockResolvedValue({ canceled: true, filePath: null, result: null }),
  pickAndAnalyzeCboFolder: vi.fn().mockResolvedValue({ canceled: true, rootPath: null, output: null }),
  listCboRuns: vi.fn().mockResolvedValue([]),
  getCboRunDetail: vi.fn().mockResolvedValue({ run: {}, files: [] }),
  syncCboRunKnowledge: vi.fn().mockResolvedValue({ runId: '', mode: 'bulk', endpoint: '', totalCandidates: 0, synced: 0, failed: 0, failures: [] }),
  diffCboRuns: vi.fn().mockResolvedValue({ fromRunId: '', toRunId: '', added: 0, resolved: 0, persisted: 0, changes: [] }),
  cancelCboFolder: vi.fn().mockResolvedValue(undefined),
  onCboProgress: vi.fn().mockReturnValue(() => {}),
  listAuditLogs: vi.fn().mockResolvedValue([]),
  searchAuditLogs: vi.fn().mockResolvedValue([]),
  listVaultEntries: vi.fn().mockResolvedValue([]),
  searchVaultByClassification: vi.fn().mockResolvedValue([]),
  listVaultByDomainPack: vi.fn().mockResolvedValue([]),
  mcpConnect: vi.fn().mockResolvedValue({ connected: true, name: 'test-server' }),
  mcpDisconnect: vi.fn().mockResolvedValue({ disconnected: true }),
  mcpListServers: vi.fn().mockResolvedValue([]),
  mcpListResources: vi.fn().mockResolvedValue([
    { uri: 'file:///docs/guide.md', name: 'guide.md', description: 'User guide' },
  ]),
  mcpAddSource: vi.fn().mockResolvedValue({
    source: {
      id: 'mcp-src1',
      kind: 'mcp',
      title: 'Test MCP Server',
      rootPath: null,
      domainPack: 'ops',
      classificationDefault: 'reference',
      includeGlobs: [],
      enabled: true,
      syncStatus: 'ready',
      lastIndexedAt: new Date().toISOString(),
      documentCount: 1,
      connectionMeta: { serverName: 'test-server', command: 'node', args: 'server.js' },
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    summary: { indexed: 1, updated: 0, unchanged: 0, removed: 0, skipped: 0, failed: 0 },
  }),
  mcpSyncSource: vi.fn().mockResolvedValue({
    source: null,
    summary: { indexed: 1, updated: 0, unchanged: 0, removed: 0, skipped: 0, failed: 0 },
  }),
  listSessionsFiltered: vi.fn().mockResolvedValue([]),
  updateSessionTodoState: vi.fn().mockResolvedValue(undefined),
  toggleSessionFlag: vi.fn().mockResolvedValue(undefined),
  toggleSessionArchive: vi.fn().mockResolvedValue(undefined),
  addSessionLabel: vi.fn().mockResolvedValue(undefined),
  removeSessionLabel: vi.fn().mockResolvedValue(undefined),
  getSessionStats: vi.fn().mockResolvedValue({
    all: 0, open: 0, analyzing: 0, "in-progress": 0,
    resolved: 0, closed: 0, flagged: 0, archived: 0,
  }),
  listPlans: vi.fn().mockResolvedValue([]),
  getPlan: vi.fn().mockResolvedValue(null),
  createPlan: vi.fn().mockResolvedValue({ id: 'plan-1', title: '테스트 Plan', type: 'monthly', targetDate: '2026-03-31', status: 'in-progress', progressPercent: 0, createdAt: '', updatedAt: '' }),
  updatePlan: vi.fn().mockResolvedValue(null),
  deletePlan: vi.fn().mockResolvedValue(true),
  listPlansByStatus: vi.fn().mockResolvedValue([]),
  listOverduePlans: vi.fn().mockResolvedValue([]),
  listSteps: vi.fn().mockResolvedValue([]),
  createStep: vi.fn().mockResolvedValue({ id: 'step-1', planId: 'plan-1', title: '테스트 Step', deadline: '2026-03-31', status: 'pending', sortOrder: 0, createdAt: '', updatedAt: '' }),
  updateStep: vi.fn().mockResolvedValue(null),
  deleteStep: vi.fn().mockResolvedValue(true),
  reorderSteps: vi.fn().mockResolvedValue(undefined),
  getClosingStats: vi.fn().mockResolvedValue({ totalPlans: 0, completedPlans: 0, delayedPlans: 0, inProgressPlans: 0, totalSteps: 0, completedSteps: 0, overdueSteps: 0, imminentSteps: 0 }),
  getOAuthAvailability: vi.fn().mockResolvedValue([
    { provider: 'openai', available: true },
    { provider: 'anthropic', available: false },
    { provider: 'google', available: false },
  ]),
  initiateOAuth: vi.fn().mockResolvedValue({
    authUrl: 'https://auth.openai.com/authorize?...',
    provider: 'openai',
    useCallbackServer: true,
  }),
  waitOAuthCallback: vi.fn().mockResolvedValue({
    provider: 'openai',
    status: 'authenticated',
    accountHint: 'user@example.com',
    authType: 'oauth',
    updatedAt: new Date().toISOString(),
  }),
  cancelOAuth: vi.fn().mockResolvedValue(undefined),
  submitOAuthCode: vi.fn().mockResolvedValue({
    provider: 'anthropic',
    status: 'authenticated',
    accountHint: 'user@anthropic.com',
    authType: 'oauth',
    updatedAt: new Date().toISOString(),
  }),
  // GitHub Device Code (Copilot)
  initiateDeviceCode: vi.fn().mockResolvedValue({
    userCode: 'ABCD-1234',
    verificationUri: 'https://github.com/login/device',
    expiresIn: 900,
    interval: 5,
  }),
  pollDeviceCode: vi.fn().mockResolvedValue({
    provider: 'copilot',
    status: 'authenticated',
    accountHint: 'github-user',
    authType: 'oauth',
    updatedAt: new Date().toISOString(),
  }),
  cancelDeviceCode: vi.fn().mockResolvedValue(undefined),
  // Routine (루틴 업무 자동화)
  listRoutineTemplates: vi.fn().mockResolvedValue([]),
  listRoutineTemplatesByFrequency: vi.fn().mockResolvedValue([]),
  getRoutineTemplate: vi.fn().mockResolvedValue(null),
  createRoutineTemplate: vi.fn().mockResolvedValue({ id: 'rt-1', frequency: 'daily', name: '테스트 루틴', isActive: true, createdAt: '', updatedAt: '' }),
  updateRoutineTemplate: vi.fn().mockResolvedValue(null),
  deleteRoutineTemplate: vi.fn().mockResolvedValue(true),
  toggleRoutineTemplate: vi.fn().mockResolvedValue(null),
  executeRoutinesNow: vi.fn().mockResolvedValue({ created: 0, skipped: 0 }),
  listRoutineExecutions: vi.fn().mockResolvedValue([]),
  getRoutineExecutionPlanIds: vi.fn().mockResolvedValue([]),

  // Archive (소스코드 아카이브)
  archivePickFolder: vi.fn().mockResolvedValue({ canceled: true, path: null }),
  archiveListContents: vi.fn().mockResolvedValue([]),
  archiveReadFile: vi.fn().mockResolvedValue({ content: '', size: 0 }),
  archiveSaveFile: vi.fn().mockResolvedValue({ success: true }),

  // Agent (스킬 조합 워크플로우)
  listAgents: vi.fn().mockResolvedValue([]),
  getAgent: vi.fn().mockResolvedValue(null),
  executeAgent: vi.fn().mockResolvedValue('exec-1'),
  getAgentExecution: vi.fn().mockResolvedValue(null),
  listAgentExecutions: vi.fn().mockResolvedValue([]),
  cancelAgentExecution: vi.fn().mockResolvedValue(undefined),

  // 커스텀 에이전트 CRUD
  listCustomAgents: vi.fn().mockResolvedValue([]),
  saveCustomAgent: vi.fn().mockResolvedValue(undefined),
  deleteCustomAgent: vi.fn().mockResolvedValue(undefined),
  openAgentFolder: vi.fn().mockResolvedValue(undefined),

  // 커스텀 스킬 CRUD
  listCustomSkills: vi.fn().mockResolvedValue([]),
  saveCustomSkill: vi.fn().mockResolvedValue(undefined),
  deleteCustomSkill: vi.fn().mockResolvedValue(undefined),
  openSkillFolder: vi.fn().mockResolvedValue(undefined),
}

Object.defineProperty(window, 'sapOpsDesktop', {
  value: mockApi,
  writable: true,
})

// 각 테스트 전에 모든 mock 초기화
beforeEach(() => {
  Object.values(mockApi).forEach((fn) => fn.mockClear())
})

// workspaceStore 초기화를 위한 헬퍼
export function resetWorkspaceStore() {
  useWorkspaceStore.setState({
    domainPack: 'ops',
  })
}

export { mockApi }
